module.exports = {
	encounterMap: {
		Valtan: {
			"Valtan G1": [
				"Dark Mountain Predator",
				"Destroyer Lucas",
				"Leader Lugaru",
			],
			"Valtan G2": ["Demon Beast Commander Valtan", "Ravaged Tyrant of Beasts"],
		},
		Vykas: {
			"Vykas G1": ["Incubus Morphe", "Nightmarish Morphe"],
			"Vykas G2": ["Covetous Devourer Vykas"],
			"Vykas G3": ["Covetous Legion Commander Vykas"],
		},
		Clown: {
			"Clown G1": ["Saydon"],
			"Clown G2": ["Kakul"],
			"Clown G3": ["Kakul-Saydon", "Encore-Desiring Kakul-Saydon"],
		},
		Brelshaza: {
			Brelshaza: ["Brelshaza"],
			"Brelshaza G1": ["Gehenna Helkasirs"],
			"Brelshaza G2": ["Prokel", "Prokel's Spiritual Echo", "Ashtarot"],
			"Brelshaza G3": ["Primordial Nightmare"],
			"Brelshaza G4": ["Phantom Legion Commander Brelshaza"],
			"Brelshaza G5": [
				"Brelshaza, Monarch of Nightmares",
				"Imagined Primordial Nightmare",
				"Pseudospace Primordial Nightmare",
			],
			"Brelshaza G6": ["Phantom Legion Commander Brelshaza"],
		},
		Kayangel: {
			"Kayangel G1": ["Tienis"],
			"Kayangel G2": ["Prunya"],
			"Kayangel G3": ["Lauriel"],
		},
		Akkan: {
			"Akkan G1": ["Griefbringer Maurug", "Evolved Maurug"],
			"Akkan G2": ["Lord of Degradation Akkan", "Decaying Kin"],
			"Akkan G3": ["Plague Legion Commander Akkan", "Lord of Kartheon Akkan"],
		},
		Ivory: {
			"Ivory Tower G1": ["Kaltaya, the Blooming Chaos"],
			"Ivory Tower G2": ["Rakathus, the Lurking Arrogance"],
			"Ivory Tower G3": ["Firehorn, Trampler of Earth"],
			"Ivory Tower G4": [
				"Origin of Lazaram",
				"Lazaram, the Trailblazer",
				"Subordinated Vertus",
				"Subordinated Calventus",
				"Subordinated Legoros",
				"Brand of Subordination",
			],
		},
		Thaemine: {
			"Thaemine G1": [
				"Killineza the Dark Worshipper",
				"Tentacle of Darkness",
				"Killineza's Eye",
			],
			"Thaemine G2": [
				"Valinak, Knight of Darkness",
				"Valinak, Taboo Usurper",
				"Valinak, Herald of the End",
				"Valinak",
				"Dark Membrane",
			],
			"Thaemine G3": ["Thaemine the Lightqueller", "Dark Greatsword"],
			"Thaemine G4": [
				"Darkness Legion Commander Thaemine",
				"Thaemine Prokel",
				"Thaemine, Conqueror of Stars",
			],
		},
		Echidna: {
			"Echidna G1": ["Red Doom Narkiel", "Agris", "Agris's Illusion"],
			"Echidna G2": [
				"Echidna",
				"Covetous Master Echidna",
				"Desire in Full Bloom, Echidna",
				"Alcaone, the Twisted Venom",
				"Agris, the Devouring Bog",
			],
		},
		Behemoth: {
			"Behemoth G1": [
				"Behemoth, the Storm Commander",
				"Despicable Skolakia",
				"Untrue Crimson Yoho",
				"Ruthless Lakadroff",
				"Vicious Argeos",
			],
			"Behemoth G2": ["Behemoth, Cruel Storm Slayer"],
		},
		Aegir: {
			"Aegir G1": ["Akkan, Lord of Death", "Abyss Monarch Aegir"],
			"Aegir G2": ["Aegir, the Oppressor", "Pulsating Giant's Heart"],
		},
		AbyssalDungeon: {
			Abyss: [
				"Phantom Legion Bishop",
				"Phantom Legion Rook",
				"Phantom Legion King",
				"Phantom Legion Queen",
				"Darkness Legion Kiril",
				"Darkness Legion Veromek",
				"Darkness Legion Zoldat",
				"Red Pirate",
				"Divided Parts of Arrogance",
				"Mayhem Legion Shamok",
				"Mayhem Legion Seto",
				"Mayhem Legion Skutoom",
				"Mayhem Legion Stella",
				"Monster",
				"Nazan",
				"Kyzra",
				"Amaus",
				"Kaishur",
			],
		},
		GuardianRaids: {
			Guardians: [
				"Argeos",
				"Veskal",
				"Gargadeth",
				"Sonavel",
				"Hanumatan",
				"Kungelanium",
				"Deskaluda",
				"Ur'nil+",
				"Dark Legoros+",
				"Levanos Core",
				"Levanos",
				"Lumerus+",
				"Vertus",
				"Flame Guardian",
				"Frost Guardian",
				"Helgaia",
				"Achates",
				"Night Fox Yoho",
				"Aurion",
			],
		},
		UnknownBoss: {
			Boss: [
				"Eikerr",
				"Sword of Corruption, Lir",
				"Vile Scarkrill",
				"Reanimated Garum",
				"Drakus",
				"Wilhelm",
				"Revellos",
				"Osphere",
				"Agherun",
				"Mucus Demon Mukus",
				"Abyssal Unos",
				"Sevek Atun",
				"Belmorok",
				"Sea God Aporas",
				"Giant Toxic Cluster",
				"Seething Blood Levantalos",
				"Faithless Kario",
				"Chaotic Zaika",
				"Behemoth, the Whirling Wings of Chaos",
				"Sett, the First Vinus",
				"Plague Legion Loogdoom",
				"Plague Legion Gurzar",
				"Plague Legion Vagnos",
				"Plague Legion Epidemikus",
				"Giant Homunculus",
				"Labyrinth Guardian",
				"Sigmund",
				"Tikatika Chameleon",
				"White Mage",
				"Habeck",
				"Chaotic Skolakia",
				"Stella",
				"Corrupting Light Leshar",
				"Naber",
			],
		},
	},

	difficultyMap: [
		"Normal",
		"Hard",
		"Inferno",
		"Challenge",
		"Solo",
		"Trial",
		"Extreme",
		"The First",
	],
};
